name: IPTV M3U Maker

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run IPTV script
      run: python python/iptv.py

    - name: Show tv.m3u content
      run: |
        echo "tv.m3u content:"
        cat http/tv.m3u || echo "tv.m3u not found"

    - name: Upload tv.m3u as artifact
      uses: actions/upload-artifact@v4
      with:
        name: tv.m3u
        path: http/tv.m3u
