name: IPTV Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 00:00 运行
  workflow_dispatch:  # 支持手动触发

jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: List directory structure
        run: ls -R  # 调试：显示目录结构

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run IPTV crawler
        run: python iptv.py
        working-directory: python  # 运行 python 目录下的 iptv.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: iptv-files
          path: |
            python/encrypted_urls.txt
            python/tv.m3u
            python/tv.json
            python/log.txt

      - name: Check directory after run
        run: ls -l python/ || echo "Directory check failed"
        working-directory: python
        if: always()

      - name: Run decryption
        run: python decrypt.py
        working-directory: python
        if: success()

      - name: Upload decrypted files
        uses: actions/upload-artifact@v4
        with:
          name: decrypted-files
          path: python/decrypted_urls.txt
          if: success()

      - name: Display log content (debug)
        run: cat log.txt || echo "No log file found"
        working-directory: python
        if: always()  # 无论成功与否都运行
